# name: Changesets

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write
#   pull-requests: write

# jobs:
#   version:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4

#       - name: Install pnpm
#         uses: pnpm/action-setup@v4
#       - run: corepack enable pnpm

#       - run: pnpm install --frozen-lockfile

#       - name: Create Release Pull Request
#         uses: changesets/action@v1
#         with:
#           version: pnpm run version-packages
#           publish: pnpm run release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
